server:
  # 端口
  port: 9090

#---Sa-Token 配置---
sa-token:
  # --token 名称（同时也是 cookie 名称）
  token-name: satoken
  # --token 有效期一天（单位：秒）
  timeout: 86400
  # --token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # --是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # --在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # --token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # --是否输出操作日志
  is-log: true

#---Spring配置---
spring:
  application:
    name: core-framework
  servlet:
    # --文件上传大小限制
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  #---MySQL数据配置---(暂定本地数据库、可迁移至docker)
  datasource:
    url: jdbc:mysql://192.168.191.128:3306/eeveeagent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.191.128
      port: 6379
      password: 123456

#---Mybatis-Plus配置---
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.azheng.framework.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



langchain4j:
  #---百炼平台-通义千问核心配置---
  community:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      dimensions: 2048
  # --OpenAI
  open-ai:

#---Milvus 向量数据库配置---
milvus:
  uri: http://192.168.191.128:19530
  dbname: eevee_agent
  connectTimeout: 5000
  keepAliveTime: 30000
  idleTimeout: 60000


#---RustFS 对象存储配置---
rustfs:
  url: http://192.168.191.128:9000
  # --账号密码
  access-key-id: rustfsadmin
  secret-access-key: rustfsadmin

#---RAG 向量库基础配置---
rag:
  default:
    collection-name: rag_default_store   # Milvus 集合名（知识库表）
    dimension: 2048                     # 向量维度 → 必须和 embedding 模型一致
    metric-type: COSINE                 # 相似度算法（余弦相似度，正确）


intent:
  topk: 30





